runtime: python37
#api_version: 1
##threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /.*
  secure: always
  script: auto


instance_class: B4_1G
basic_scaling:
  max_instances: 11
  idle_timeout: 10m

env_variables:
  BUCKET_NAME: gps_map