runtime: python37
#api_version: 1
##threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /.*
  secure: always
  script: auto


instance_class: F4_1G
automatic_scaling:
  target_cpu_utilization: 0.6 # default value
  target_throughput_utilization: 0.6 # default value
  max_instances: 5
  min_instances: 5
  max_idle_instances: automatic  # default value
  min_idle_instances: 3
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 80

env_variables:
  BUCKET_NAME: gps_map

