

service: web-yacht-note-app

runtime: python37
api_version: 1
#threadsafe: yes

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: app.app

#libraries:
#- name: ssl
#  version: latest
#
#- name: jinja2
#  version: latest